# Generated by Django 3.0.7 on 2020-06-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_sites',
            name='site_logo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
