# Generated by Django 3.0.7 on 2020-06-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcbook', '0003_services_bal_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
