# Generated by Django 3.0.7 on 2020-06-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcbook', '0004_auto_20200615_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
